apiVersion: v1
kind: Secret
metadata:
  name: encryption-secret
  namespace: banking
type: Opaque
stringData:
  # Dev-only key - not a real secret, same value used in docker-compose.yml. Used by
  # payment-core-service and gateway-service to decrypt User.fullName consistently.
  encryption-key: mzD/i0fiHcYLv3g0wwTlvAp49wYo1MFNRYBM/f52XPI=
